language: c
sudo: required
services:
  - docker
script:
  - make docker-cflakes-build docker-cflakes
deploy:
  provider: script
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push epilanthanomai/cflakes
  on:
    branch:
      - develop
