language: c
sudo: required
services:
  - docker
script:
  - docker build -t epilanthanomai/cflakes .
deploy:
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push epilanthanomai/cflakes
  on:
    branch:
      master
